In [1]:
!pip install Faker

Requirement already satisfied: Faker in c:\users\surjayandutta\anaconda3\envs\synthetic_data\lib\site-packages (29.0.0)
Requirement already satisfied: python-dateutil>=2.4 in c:\users\surjayandutta\anaconda3\envs\synthetic_data\lib\site-packages (from Faker) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\surjayandutta\anaconda3\envs\synthetic_data\lib\site-packages (from python-dateutil>=2.4->Faker) (1.16.0)

In [2]:
from faker import Faker
fake = Faker()

In [3]:
print(fake.name())

Craig Eaton

In [4]:
print(fake.address())

80962 Kristen Loop
North Johnside, UT 10506

In [5]:
for _ in range(5):
    print(fake.name())

John Simmons
Cameron Mercado
Joshua Casey
Joshua Garcia
Christine Perez

In [6]:
print(fake.address())

Unit 8887 Box 9410
DPO AE 33548

In [7]:
print(fake.email())

teresa45@example.net

In [8]:
from faker import Faker
import pandas as pd
import random

In [9]:
!pip install gender-guesser

Requirement already satisfied: gender-guesser in c:\users\surjayandutta\anaconda3\envs\synthetic_data\lib\site-packages (0.4.0)

In [10]:
import gender_guesser.detector as gender

fake = Faker()
gender_detector = gender.Detector()

In [11]:
# Function to generate gender-consistent names
def get_gender_consistent_name(gender_code):
    while True:
        if gender_code == 'M':
            first_name = fake.first_name_male()
        else:
            first_name = fake.first_name_female()
        
        # Guess gender by name using gender-guesser
        guessed_gender = gender_detector.get_gender(first_name)
        
        # Check if the gender matches the code ('male' for 'M' and 'female' for 'F')
        if (gender_code == 'M' and guessed_gender in ['male', 'mostly_male']) or \
           (gender_code == 'F' and guessed_gender in ['female', 'mostly_female']):
            break

    return first_name

In [12]:
# Function to generate a 10-digit US phone number
def generate_us_phone_number():
    # US phone number: (XXX) XXX-XXXX format
    area_code = random.randint(200, 999)  # Valid area codes usually between 200-999
    central_office_code = random.randint(200, 999)  # First digit can't be 0 or 1
    line_number = random.randint(1000, 9999)  # The last 4 digits
    return f"({area_code}) {central_office_code}-{line_number}"

In [13]:
# Function to generate a more realistic email address
def generate_email(first_name, last_name):
    domains = ['gmail.com', 'yahoo.com', 'hotmail.com', 'outlook.com']
    domain = random.choice(domains)
    
    # Create different variations of email using first name and last name
    email_variations = [
        f"{first_name.lower()}.{last_name.lower()}@{domain}",
        f"{first_name[0].lower()}{last_name.lower()}@{domain}",
        f"{first_name.lower()}{last_name[0].lower()}@{domain}",
        f"{first_name.lower()}{random.randint(1, 99)}@{domain}",
        f"{first_name.lower()}_{last_name.lower()}@{domain}",
    ]
    
    return random.choice(email_variations)

In [119]:
# Function to generate synthetic member data
def generate_synthetic_data(num_rows):
    data = []
    
    # Keep track of unique values for certain columns
    member_ids = set()
    group_ids = set()
    benefit_ids = set()
    phone_numbers = set()
    emails = set()
    
    for _ in range(num_rows):
        # Generate unique Member ID
        while True:
            member_id = random.randint(100000000, 999999999)
            if member_id not in member_ids:
                member_ids.add(member_id)
                break
        
        # Generate unique Group ID related to Member ID
        while True:
            group_id = f"{member_id}GP"
            if group_id not in group_ids:
                group_ids.add(group_id)
                break

        # Generate unique Benefit ID
        while True:
            benefit_id = random.randint(100000, 999999)
            if benefit_id not in benefit_ids:
                benefit_ids.add(benefit_id)
                break

        # Generate Gender and ensure it's consistent with the name
        gender_code = random.choice(['M', 'F'])
        first_name = get_gender_consistent_name(gender_code)
        last_name = fake.last_name()

        # Ensure age is below 80 and above 0
        birth_date = fake.date_of_birth(minimum_age=0, maximum_age=80)
        
        # Ensure unique 10-digit US phone number
        while True:
            phone_number = generate_us_phone_number()
            if phone_number not in phone_numbers:
                phone_numbers.add(phone_number)
                break

        #Generate a realistic emails
        while True:
            email = generate_email(first_name, last_name)
            if email not in emails:
                emails.add(email)
                break
        
        # Financials
        deductible_max = round(random.uniform(100, 1000), 2)
        accumulated_deductible = round(random.uniform(0, deductible_max), 2)

        oop_max = round(random.uniform(1000, 5000), 2)
        accumulated_oop = round(random.uniform(0, oop_max), 2)
        
        # Append row to the data
        data.append({
            'Member_Id': member_id,
            'Member_Dep_Num': random.randint(1, 100),
            'Member_First_Name': first_name,
            'Member_Last_Name': last_name,
            'Member_Middle_Initial': fake.random_letter().upper(),
            'Group_ID': group_id,
            'Member_Address_Text': fake.street_address(),
            'Member_City_Name': fake.city(),
            'Member_County_Name': fake.city(),
            'State_CD': fake.state_abbr(),
            'State_Name': fake.state(),
            'Member_Zip_Code': fake.zipcode(),
            'Member_email_id': email,
            'Member_phone_Number': phone_number,
            'Gender_Code': gender_code,
            'Member_Birth_Date': birth_date.strftime("%Y-%m-%d"),
            'Member_benefit_Id': benefit_id,
            'Member_Benefit_Name': f'member_benefit_name_{member_id}',
            'Deductible_Max': deductible_max,
            'OOP_Max': oop_max,
            'Accumulated_Deductable': accumulated_deductible,
            'Accumulated_OOP': accumulated_oop
        })

    # Convert list to DataFrame
    df = pd.DataFrame(data)
    return df

In [198]:
num_rows = int(input("Enter the number of rows to generate: "))
df1 = generate_synthetic_data(num_rows)

Enter the number of rows to generate:  200

In [199]:
df1

,Member_Id,Member_Dep_Num,Member_First_Name,Member_Last_Name,Member_Middle_Initial,Group_ID,Member_Address_Text,Member_City_Name,Member_County_Name,State_CD,...,Member_email_id,Member_phone_Number,Gender_Code,Member_Birth_Date,Member_benefit_Id,Member_Benefit_Name,Deductible_Max,OOP_Max,Accumulated_Deductable,Accumulated_OOP
0,521637386,2,Lisa,Williams,D,521637386GP,02491 Jacqueline Summit,Walkershire,Johnsonfurt,PA,...,lisa46@gmail.com,(891) 286-5405,F,2015-08-13,582797,member_benefit_name_521637386,241.63,2810.28,38.78,255.01
1,613512272,83,Olivia,Jones,K,613512272GP,9726 Huffman Extension Apt. 323,Port Billy,New Brookemouth,PR,...,oliviaj@hotmail.com,(995) 273-4069,F,1955-12-07,907616,member_benefit_name_613512272,175.32,2870.18,29.89,1664.05
2,168971061,27,Marissa,Martin,T,168971061GP,05906 Jennifer Creek Apt. 702,North Laurenbury,Martinhaven,VA,...,marissa25@yahoo.com,(912) 979-1314,F,1981-12-17,300973,member_benefit_name_168971061,964.80,2924.39,836.36,153.09
3,151275119,10,Sean,Hodges,L,151275119GP,6560 Farrell Forest Suite 775,New Nathan,Lake Jennifer,VI,...,shodges@outlook.com,(238) 529-8654,M,1991-05-10,289241,member_benefit_name_151275119,318.58,4924.80,169.29,1933.13
4,629322798,77,Mary,Diaz,W,629322798GP,4021 Stephanie Center Apt. 520,Port Crystal,Port Andreaburgh,SC,...,mary15@gmail.com,(778) 966-1018,F,1983-10-25,352176,member_benefit_name_629322798,612.13,4308.32,544.15,2854.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,592048658,74,Gabriel,Mcgee,F,592048658GP,514 Anthony Path Suite 995,South Cheyenneborough,Johnsonshire,NJ,...,gabriel_mcgee@yahoo.com,(613) 495-2594,M,2014-12-04,877609,member_benefit_name_592048658,476.54,4125.09,228.87,2854.80
196,188609297,29,William,Hall,T,188609297GP,28750 Aaron Islands,Banksville,Lake Danielberg,VT,...,william_hall@hotmail.com,(844) 974-6505,M,2006-04-13,642111,member_benefit_name_188609297,500.49,1932.97,203.75,500.14
197,172286977,96,George,Baldwin,M,172286977GP,5290 Jessica Orchard,Vincentberg,Spencerhaven,ID,...,george14@yahoo.com,(494) 206-6401,M,2016-02-27,839750,member_benefit_name_172286977,228.16,4933.46,36.52,902.80
198,741946804,18,Matthew,Jackson,J,741946804GP,2067 Steven Springs,Beckerburgh,East Christy,WA,...,matthew.jackson@yahoo.com,(255) 571-1188,M,2018-08-28,829597,member_benefit_name_741946804,376.99,2148.55,320.87,1506.84
199,593290660,47,Maurice,Shields,Q,593290660GP,308 Schmitt Lights,Garnerchester,Port Mary,ME,...,mshields@gmail.com,(461) 804-1700,M,1996-06-05,972503,member_benefit_name_593290660,169.93,4111.58,116.61,1263.85

In [174]:
type(df1)

pandas.core.frame.DataFrame

In [175]:
df1.to_csv('output.csv', index=False)

In [176]:
import numpy as np
import pandas as pd

In [200]:
def add_elv_custom_claim_adj_line_columns(df, max_claim_adj_num=3, max_claim_line_num=3):
    num_rows = len(df)
    
    # Initialize lists for the new columns
    claim_num_list = []
    adj_num_list = []
    line_num_list = []
    
    # Randomly generate the starting claim number
    current_claim_num = random.randint(10000000, 99999999)  # Random 8-digit starting claim number

    # Loop to generate the required number of combinations
    while len(claim_num_list) < num_rows:
        # Randomly choose the number of adjustments and lines for this claim_num
        claim_adj_num = random.randint(1, max_claim_adj_num)
        claim_line_num = random.randint(1, max_claim_line_num)
        
        for adj in range(claim_adj_num):
            for line in range(1, claim_line_num + 1):
                if len(claim_num_list) < num_rows:  # Check if we still need more rows
                    claim_num_list.append(current_claim_num)
                    adj_num_list.append(adj)
                    line_num_list.append(line)
        
        # Increment claim number for the next set of combinations
        current_claim_num += 1

    # Ensure lists have the correct number of entries
    claim_num_list = claim_num_list[:num_rows]
    adj_num_list = adj_num_list[:num_rows]
    line_num_list = line_num_list[:num_rows]
    
    # Insert new columns in the dataframe
    df.insert(0, 'claim_num', claim_num_list)
    df.insert(1, 'claim_adj_num', adj_num_list)
    df.insert(2, 'claim_line_num', line_num_list)

    return df

In [201]:
modified_df = add_elv_custom_claim_adj_line_columns(df1)

In [202]:
df1

,claim_num,claim_adj_num,claim_line_num,Member_Id,Member_Dep_Num,Member_First_Name,Member_Last_Name,Member_Middle_Initial,Group_ID,Member_Address_Text,...,Member_email_id,Member_phone_Number,Gender_Code,Member_Birth_Date,Member_benefit_Id,Member_Benefit_Name,Deductible_Max,OOP_Max,Accumulated_Deductable,Accumulated_OOP
0,38983025,0,1,521637386,2,Lisa,Williams,D,521637386GP,02491 Jacqueline Summit,...,lisa46@gmail.com,(891) 286-5405,F,2015-08-13,582797,member_benefit_name_521637386,241.63,2810.28,38.78,255.01
1,38983026,0,1,613512272,83,Olivia,Jones,K,613512272GP,9726 Huffman Extension Apt. 323,...,oliviaj@hotmail.com,(995) 273-4069,F,1955-12-07,907616,member_benefit_name_613512272,175.32,2870.18,29.89,1664.05
2,38983027,0,1,168971061,27,Marissa,Martin,T,168971061GP,05906 Jennifer Creek Apt. 702,...,marissa25@yahoo.com,(912) 979-1314,F,1981-12-17,300973,member_benefit_name_168971061,964.80,2924.39,836.36,153.09
3,38983027,0,2,151275119,10,Sean,Hodges,L,151275119GP,6560 Farrell Forest Suite 775,...,shodges@outlook.com,(238) 529-8654,M,1991-05-10,289241,member_benefit_name_151275119,318.58,4924.80,169.29,1933.13
4,38983027,1,1,629322798,77,Mary,Diaz,W,629322798GP,4021 Stephanie Center Apt. 520,...,mary15@gmail.com,(778) 966-1018,F,1983-10-25,352176,member_benefit_name_629322798,612.13,4308.32,544.15,2854.53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,38983075,0,1,592048658,74,Gabriel,Mcgee,F,592048658GP,514 Anthony Path Suite 995,...,gabriel_mcgee@yahoo.com,(613) 495-2594,M,2014-12-04,877609,member_benefit_name_592048658,476.54,4125.09,228.87,2854.80
196,38983075,0,2,188609297,29,William,Hall,T,188609297GP,28750 Aaron Islands,...,william_hall@hotmail.com,(844) 974-6505,M,2006-04-13,642111,member_benefit_name_188609297,500.49,1932.97,203.75,500.14
197,38983075,0,3,172286977,96,George,Baldwin,M,172286977GP,5290 Jessica Orchard,...,george14@yahoo.com,(494) 206-6401,M,2016-02-27,839750,member_benefit_name_172286977,228.16,4933.46,36.52,902.80
198,38983076,0,1,741946804,18,Matthew,Jackson,J,741946804GP,2067 Steven Springs,...,matthew.jackson@yahoo.com,(255) 571-1188,M,2018-08-28,829597,member_benefit_name_741946804,376.99,2148.55,320.87,1506.84
199,38983076,0,2,593290660,47,Maurice,Shields,Q,593290660GP,308 Schmitt Lights,...,mshields@gmail.com,(461) 804-1700,M,1996-06-05,972503,member_benefit_name_593290660,169.93,4111.58,116.61,1263.85

In [204]:
df1.to_csv('outputt.csv',index= False )